# docker-compose.yml

version: '2'

services:
  boca:
    image: decomp/boca
    container_name: boca
    ports:
      - 8090:80
    depends_on:
      - postgres-boca
    environment:
      DBHOST: postgres-boca
      DBUSER: bocauser
      DBNAME: bocadb
      DBPASS: boca
    links:
      - postgres-boca
    networks:
      - boca-network  
  boca-jail:
    image: decomp/boca-jail
    container_name: boca-jail
    privileged: true
    depends_on:
      - boca
      - postgres-boca
    environment:
      DBHOST: postgres-boca
      DBUSER: bocauser
      DBNAME: bocadb
      DBPASS: boca
    links:
      - postgres-boca
    networks:
      - boca-network  
  postgres-boca:
    image: postgres
    container_name: postgres-boca
    environment:
      POSTGRES_USER: bocauser
      POSTGRES_PASSWORD: boca
    networks:
      - boca-network  
networks:
 boca-network:
     driver: bridge
